[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  GENERATE_SOURCEMAP = "false"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
to: https://sistemafinanzas-vp-backend.onrender.com/api/:splat
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200